<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add To Cart</title>
</head>
<body>
<div>
    <form id="cart-form" action="checkout/cart/add">
        <?php echo $block->getBlockHtml('formkey') ?>

        <input type="hidden" name="myController" value="1">

        <div class="form-data">
            <label for="sku">Product SKU</label>
            <input id="sku" name="sku" type="text" placeholder="Enter product SKU"
                   list="info" autocomplete="off" required/>
        </div>

        <datalist id="info">
        </datalist>

        <div class="form-data">
            <label for="quantity">Product quantity</label>
            <input id="quantity" name="quantity" type="text" placeholder="Enter quantity" required/>
        </div>

        <div class="form-data">
            <button class="action tocart primary" id="add" type="submit" name="addToCart">Add To Cart</button>
            <button class="action tocart primary" id="reset" type="reset" name="clearValues">Reset</button>
        </div>
    </form>
</div>
</body>
</html>
