<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */

?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add To Cart</title>
</head>
<body>
<div>
    <form id="cart-form" action="<?= $block->getUrl('*/cart/addtocart') ?>" >
        <p>
            <label for="sku">Product SKU</label>
            <input name="sku" type="text" placeholder="Enter product SKU">
            <label for="quantity">Product quantity</label>
            <input name="quantity" type="text" placeholder="Enter quantity">
            <button class="action tocart primary" type="submit" name="addToCart">Add To Cart</button>
        </p>
    </form>
</div>
</body>
</html>

