<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */

?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add To Cart</title>
</head>
<body>
<div>
    <form id="cart-form" action="<?= $block->getUrl('*/cart/add') ?>" >
        <p>
            <label for="sku">Product SKU</label>
            <input  id="sku" name="sku" type="text" placeholder="Enter product SKU" list="info" autocomplete="off" required/>
            <datalist id="info">
            </datalist>
            <label for="quantity">Product quantity</label>
            <input id="quantity" name="quantity" type="text" placeholder="Enter quantity" required/>
            <button class="action tocart primary" type="submit" name="addToCart">Add To Cart</button>
        </p>
    </form>
</div>
</body>
</html>
